version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - namelivia
  ignore:
  - dependency-name: "@octokit/rest"
    versions:
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.2
    - 18.5.3
  - dependency-name: source-map-loader
    versions:
    - 2.0.1
